// `cloudflare-env.d.ts` (generated by `npm run cf-typegen`) only types bindings
// and vars declared in `wrangler.jsonc`. Secrets such as `BETTER_AUTH_SECRET`
// are never put in `wrangler.jsonc` (they're set via `.dev.vars` locally and
// `wrangler secret put` remotely), so we extend `CloudflareEnv` here — a
// hand-written file the generator never touches.
declare global {
  interface CloudflareEnv {
    BETTER_AUTH_SECRET: string;
  }
}

export {};
