import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // OpenNext/Wrangler build output (created by `npm run preview` /
    // `npm run deploy`); already git-ignored, never hand-written.
    ".open-next/**",
    ".wrangler/**",
    // Auto-generated by `npm run cf-typegen`; not hand-written.
    "cloudflare-env.d.ts",
    // Generated by `npx shadcn add ...`; never hand-edited (see AGENTS.md /
    // global-constraints.md), so lint issues shipped in a registry snapshot
    // (e.g. `use-mobile.ts`'s effect) can't be fixed here either.
    "src/components/ui/**",
    "src/hooks/**",
  ]),
]);

export default eslintConfig;
